coding-blocks/CBOnlineApp

- app/src/main/res/layout/activity_main.xml
Sample PR.
Signed-off-by: the-dagger <harshithdwivedi@gmail.com>
> chore : pull request example

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/codingblocks/cbonlineapp/CBOnlineApp.kt
- app/src/main/java/com/codingblocks/cbonlineapp/LoginActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/SplashActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/Utils/PreferenceHelper.kt
- app/src/main/res/drawable/button_background.xml
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/auth_dialog.xml
Added Login Activity With Shared Preferences Class
> Added Login Activity With Shared Preferences Class

- app/src/main/java/com/codingblocks/cbonlineapp/MyCourseActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionDetailsAdapter.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/ContentDao.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/DbModel.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/SectionDao.kt
- app/src/main/java/com/codingblocks/cbonlineapp/fragments/CourseContentFragment.kt
- app/src/main/res/layout/fragment_course_content.xml
- app/src/main/res/layout/item_section_content_info.xml
- onlineapi/src/main/kotlin/com/codingblocks/onlineapi/api/OnlinePublicApi.kt
Signed-off-by: pulkit-mac <aggarwalpulkit596@gmail.com>
> play videos

- .idea/misc.xml
- .idea/modules.xml
- app/src/main/java/com/codingblocks/cbonlineapp/services/DownloadService.kt
Signed-off-by: Harshit Dwivedi <the-dagger@Harshits-MacBook-Pro.local>
@aggarwalpulkit596
> fix : clear notifications once download is completed

- app/src/main/java/com/codingblocks/cbonlineapp/activities/AboutActivity.kt
- app/src/main/res/layout/activity_about.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Fixes #163 
Fixed all errors in this issue.
The address Text issue was due to the presence of some different encoded characters
possibly due to copy-pasting issues.
> feat: add info for all centres 

- app/src/main/res/menu/activity_home_drawer.xml
> fix: fixed drawer item status behaviour

- app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionDetailsAdapter.kt
- app/src/main/res/drawable/button_background.xml
- app/src/main/res/layout/item_section.xml
- app/src/main/res/layout/item_section_content_info.xml
Reverts coding-blocks/CBOnlineApp#187
> Revert "Shubham1"

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt
- app/src/main/res/layout/activity_course.xml
- app/src/main/res/layout/bottom_cart_sheet.xml
- app/src/main/res/layout/custom_dialog.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Fixes #152 
feat: major topics covered shows in the course activity
> tags section added to course activity

- app/src/main/java/com/codingblocks/cbonlineapp/fragments/HomeFragment.kt
Fixes #191 
Changes: modified condition
Screenrecording:
> fix: viewpager goes to first index after each cycle

- app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt
Fixes #193 
Changes: attached snaphelper to recyclerview
Screenrecording:
> fix: add Snaphelper to Batches Recycler View

- app/src/main/java/com/codingblocks/cbonlineapp/fragments/QuizFragment.kt
- app/src/main/res/drawable/submit_button_background.xml
- app/src/main/res/drawable/submit_image.xml
Fixes part five of #181 
Changes: Added submit button in quiz bottom sheet
On clicking submit button
> Added submit button in quiz bottom sheet

- app/src/main/java/com/codingblocks/cbonlineapp/activities/CourseActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionsDataAdapter.kt
- app/src/main/res/drawable/ic_up_arrow.xml
- app/src/main/res/layout/item_skeleton_section_card.xml
Fixes #196 
Changes: Up arrow icon added if the list expands
> feat: add shimmer to course content sections

- app/src/main/java/com/codingblocks/cbonlineapp/extensions/LiveDataExtensions.kt
Fixes Part 5 of #181 
Changes: Corrected the quiz attempt time.
> Fixed incorrect quiz attempt time

- app/src/main/java/com/codingblocks/cbonlineapp/adapters/BatchesAdapter.kt
Fixes #203 
Changes: started trial on click of start trail button
Screenreording for the change:
> functionality added to bottom start trial button

- app/src/main/java/com/codingblocks/cbonlineapp/activities/QuizActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/adapters/ViewPagerAdapter.kt
- app/src/main/java/com/codingblocks/cbonlineapp/fragments/AboutQuizFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/fragments/QuizFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/fragments/QuizResultFragment.kt
- app/src/main/res/animator/slide_in_right.xml
- app/src/main/res/animator/slide_out_left.xml
- app/src/main/res/layout/fragment_quiz_result.xml
Fixes part 1 of #181 
Changes: 
1. Submit Button Removed from already submitted quizzes
2. Quiz Result Screen does not appear in already submitted quizzes
3. Back button working on the quiz result screen.
already submitted quiz...
> Improved Quiz Flow

- app/src/main/java/com/codingblocks/cbonlineapp/fragments/AboutQuizFragment.kt
- app/src/main/res/layout/item_skeleton_quiz.xml
Fixes part 2 of #181 
Changes: Added correct skeleton layout for quiz
> Added correct skeleton layout for quiz

- app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionDetailsAdapter.kt
- app/src/main/res/drawable/button_background.xml
- app/src/main/res/layout/item_section.xml
Fixes  #164 
Changes: 1. Changed the title layout orientation from centre to top
2. Added free label 
> Added free with proper layout

- app/src/main/java/com/codingblocks/cbonlineapp/activities/NotificationsActivity.kt
Fixes #216 
Changes: Swipe to delete for notifications list
> Added swipe to delete for notifications list

- app/build.gradle
- app/src/main/java/com/codingblocks/cbonlineapp/Modules.kt
- app/src/main/java/com/codingblocks/cbonlineapp/activities/HomeActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/util/FileUtils.kt
- app/src/main/java/com/codingblocks/cbonlineapp/util/NetworkUtils.kt
- app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/HomeActivityViewModel.kt
- app/src/main/res/values/strings.xml
Fixes #218
Changes:
- Added ViewModel to Control the HomeActivity
> refactor: HomeActivityViewModel Added and more lint fixes

- app/src/main/java/com/codingblocks/cbonlineapp/activities/HomeActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/CourseRunDao.kt
- app/src/main/java/com/codingblocks/cbonlineapp/fragments/MyCoursesFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/util/MediaUtils.kt
Fixes #179 
Changes: dynamic shortcut added for course with maximum usage
Screenrecording for the change:
> dynamic shortcut added

- .idea/misc.xml
- app/src/debug/res/values/strings.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/codingblocks/cbonlineapp/CBOnlineApp.kt
- app/src/main/java/com/codingblocks/cbonlineapp/URLRouterActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/models/DbModels.kt
- app/src/main/java/com/codingblocks/cbonlineapp/extensions/LangUtilsExtensions.kt
- app/src/main/java/com/codingblocks/cbonlineapp/util/Constants.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- onlineapi/src/main/kotlin/com/codingblocks/onlineapi/models/APIModel.kt
Signed-off-by: Arnav Gupta <arnav@codingblocks.com>
Changes: 
- handles slugs null
- separate package name and title for debug app
> debug package name, slugs are null

- app/src/main/java/com/codingblocks/cbonlineapp/CBOnlineApp.kt
- app/src/main/java/com/codingblocks/cbonlineapp/URLRouterActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/extensions/LangUtilsExtensions.kt
> fix: travis build

- .idea/misc.xml
- app/src/main/java/com/codingblocks/cbonlineapp/activities/SettingsActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/adapters/SectionDetailsAdapter.kt
- app/src/main/java/com/codingblocks/cbonlineapp/extensions/PreferenceHelperExtensions.kt
- app/src/main/java/com/codingblocks/cbonlineapp/util/FileUtils.kt
- app/src/main/java/com/codingblocks/cbonlineapp/util/PreferenceHelper.kt
- app/src/main/res/drawable/seekbar_thumb.xml
- app/src/main/res/drawable/seekbar_track.xml
- app/src/main/res/layout/activity_settings.xml
- app/src/main/res/values/strings.xml
Fixes #217 
Changes: 
- added download limit for videos
https://drive.google.com/open?id=1-9UtcPkO2t4bwTCfsiqi5hHzHYIZH-qS
> feat: Download limit in Settings

- app/src/main/java/com/codingblocks/cbonlineapp/activities/QuizActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/activities/ThrowableActivity.kt
Fixes #279 
Changes:
- Removed AboutQuiz from stack. 
> fix: empty screen when back pressed on aboutquiz fragment

- app/src/main/java/com/codingblocks/cbonlineapp/activities/ThrowableActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/fragments/AboutQuizFragment.kt
Fixes #275 
Changes: 
- Clear the arraylist before adding the attempts again
> fix: duplicates in Quiz Attempts

- app/src/main/java/com/codingblocks/cbonlineapp/adapters/ViewPagerAdapter.kt
- app/src/main/java/com/codingblocks/cbonlineapp/fragments/QuizFragment.kt
Fixes #246 
Changes: invoked the confirmation dialog followed by quizresultfragment on click of submit button of view pager and end button
> confirmation dialog invoked on submit

- app/src/main/java/com/codingblocks/cbonlineapp/activities/VideoPlayerActivity.kt
- onlineapi/src/test/java/com/codingblocks/onlineapi/api/OnlineJsonApiAuthenticatedTest.kt
- onlineapi/src/test/java/com/codingblocks/onlineapi/api/OnlineRestApiAuthenticatedTest.kt
> fix: video crash when youtube video

- app/src/main/java/com/codingblocks/cbonlineapp/adapters/EndlessPagerAdapter.kt
Reverts coding-blocks/CBOnlineApp#292
> Revert "view pager scrolling smooth"

- app/src/main/res/drawable/seekbar_track.xml
Fixes #345 
Changes: 
- updated private color code
> fix: updated private color code

- app/src/main/java/com/codingblocks/cbonlineapp/database/DownloadData.kt
- app/src/main/java/com/codingblocks/cbonlineapp/services/DownloadService.kt
- app/src/main/java/com/codingblocks/cbonlineapp/util/Constants.kt
Fixes #255 
Changes: 
- added support for multiple downloads
Video for the change:
https://drive.google.com/open?id=1-0-8OQxTlfIw8TLuO2MFsfd3z18Y_ijP
> feat: support multiple downloads

- app/src/main/java/com/codingblocks/cbonlineapp/CBOnlineApp.kt
- app/src/main/java/com/codingblocks/cbonlineapp/activities/HomeActivity.kt
Fixes #215 
Changes: 
- Cleared Userdata on logout
Video for the change:
https://drive.google.com/open?id=1-3WGFLVa-hQgmQCSOqJ9Gz1AxtEdpXf1
> feat: delete all userdata on logout with confirmation

- app/src/main/java/com/codingblocks/cbonlineapp/activities/MyCourseActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/MyCourseViewModel.kt
- app/src/main/res/layout/activity_my_course.xml
- onlineapi/src/main/kotlin/com/codingblocks/onlineapi/api/OnlineJsonApi.kt
- onlineapi/src/main/kotlin/com/codingblocks/onlineapi/models/APIModel.kt
Fixes #333
Changes: 
- Allow User to reset course progress
https://drive.google.com/open?id=1-ChtpN_HCCR4y26YRdTmUCGHdvgvIZla
> feat: reset course progress

- app/src/main/java/com/codingblocks/cbonlineapp/activities/JobsActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/FilterData.kt
- app/src/main/java/com/codingblocks/cbonlineapp/viewmodels/JobsViewModel.kt
- app/src/main/java/com/codingblocks/cbonlineapp/widgets/SheetDialog.java
- app/src/main/res/drawable/ic_job_filter.xml
- app/src/main/res/drawable/rounded_dialog.xml
- app/src/main/res/layout/activity_jobs.xml
- app/src/main/res/layout/filters_tab.xml
- app/src/main/res/layout/sheet_filter.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- onlineapi/src/main/kotlin/com/codingblocks/onlineapi/api/OnlineJsonApi.kt
Fixes #349 
Changes: 
- Added Filter for Jobs
Video for the change:
https://drive.google.com/open?id=1-BObN3ZCCjmBYBthQcQxOBNZWJxk3K6O
> feat: job filter option

- app/src/main/java/com/codingblocks/cbonlineapp/home/HomeActivity.kt
- app/src/main/res/layout/app_bar_home.xml
- app/src/main/res/values/strings.xml
Fixes #410 
<p align="center">
</p>
> fix: Remove duplicate action bar setup

- onlineapi/build.gradle
> fix: Circle CI build

- app/build.gradle
- app/src/main/java/com/codingblocks/cbonlineapp/database/CourseWithInstructorDao.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/CarouselSliderAdapter.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/HomeActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/HomeFragmentUi.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/WrappingViewPager.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/mycourses/MyCoursesFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/mycourses/MyCoursesViewHolder.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/mycourses/MyCoursesViewModel.kt
- app/src/main/java/com/codingblocks/cbonlineapp/mycourse/MyCourseActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/mycourse/content/CourseContentFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/util/JWTUtils.java
- app/src/main/res/layout/activity_my_course.xml
- app/src/main/res/layout/fragment_course_content.xml
- app/src/main/res/layout/item_skeleton_content.xml
- app/src/main/res/values/strings.xml
Signed-off-by: Pulkit <aggarwalpulkit596@gmail.com>
> use popUpWindow for section list

- CONTRIBUTING.md
- README.md
Fixed some typos in README.md and CONTRIBUTING.md
> Fixed typos in readme.md and contributing.md

- app/build.gradle
- app/schemas/com.codingblocks.cbonlineapp.database.AppDatabase/21.json
- app/src/main/java/com/codingblocks/cbonlineapp/Modules.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/AppDatabase.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/BaseDao.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/ContentDao.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/CourseWithInstructorDao.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/SectionWithContentsDao.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/models/CourseInstructorHolder.kt
- app/src/main/java/com/codingblocks/cbonlineapp/database/models/SectionContentHolder.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/AllCourseFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/AllCoursesViewHolder.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/CourseDataAdapter.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/HomeActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/HomeFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/HomeRepository.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/HomeViewModel.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/mycourses/MyCoursesFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/mycourses/MyCoursesRepository.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/mycourses/MyCoursesViewHolder.kt
- app/src/main/java/com/codingblocks/cbonlineapp/home/mycourses/MyCoursesViewModel.kt
- app/src/main/java/com/codingblocks/cbonlineapp/jobs/JobsViewModel.kt
- app/src/main/java/com/codingblocks/cbonlineapp/jobs/jobdetails/JobDetailViewModel.kt
- app/src/main/java/com/codingblocks/cbonlineapp/mycourse/MyCourseRepository.kt
- app/src/main/java/com/codingblocks/cbonlineapp/mycourse/MyCourseViewModel.kt
- app/src/main/java/com/codingblocks/cbonlineapp/mycourse/content/CourseContentFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/mycourse/overview/OverviewFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/player/VideoPlayerViewModel.kt
Use Junctions and Coroutines with Room
> Room coroutines

- app/src/main/java/com/codingblocks/cbonlineapp/course/CourseActivity.kt
Fixes #473 
Changes: Change `loadVideo` to `cueVideo`
[cueVideo](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayer#cueVideo(java.lang.String))
> Fix youtube autoplay issue.

- app/src/main/java/com/codingblocks/cbonlineapp/jobs/JobsActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/jobs/JobsViewModel.kt
- app/src/main/res/layout/activity_jobs.xml
Fixes #485 
Changes:
- Fix displaying of jobs after initial fetching of jobs
- fix the problem with listAdapter.submitList() referencing list
- Add error snackbar with retry action when there is no internet for initial fetch of jobs
- Add shimmer when loading jobs
> Fix get Hired frag, add shimmer

- app/src/main/java/com/codingblocks/cbonlineapp/jobs/JobsActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/jobs/JobsViewModel.kt
- app/src/main/res/layout/activity_jobs.xml
Fixes #496 
Changes:
- Notify JobsAdapter after filtering list to fix the filter issue
- Add TextView for No jobs when no jobs are found for matching criteria
- Use of shimmer making request for filtering
> fix filter jobs

- app/src/main/java/com/codingblocks/cbonlineapp/admin/AdminActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/auth/onboarding/CompleteProfileActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/auth/onboarding/LoginHomeFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/auth/onboarding/SignInFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/util/KeyboardVisibilityUtil.kt
- app/src/main/res/layout/activity_complete_profile.xml
- app/src/main/res/layout/activity_login2.xml
- app/src/main/res/layout/fragment_login_home.xml
- app/src/main/res/values/dimens.xml
Changes: 
- Add Spannables for Privacy & TOS
- Fix overlap in LoginActivity & CompleteProfileActvity
> Add Privacy & TOS spannables, fix loginActivity for smallscreens

- app/src/main/java/com/codingblocks/cbonlineapp/commons/SheetAdapter.kt
- app/src/main/java/com/codingblocks/cbonlineapp/dashboard/mycourses/DashboardMyCoursesFragment.kt
- app/src/main/java/com/codingblocks/cbonlineapp/util/Constants.kt
- app/src/main/java/com/codingblocks/cbonlineapp/util/extensions/ViewExtensions.kt
- Add sharedPref extensions
- highlight selected item 
- save last selected item in sharedpref in  mycoursedashboardfragment
> Add sharedPref extensions

- app/src/main/java/com/codingblocks/cbonlineapp/dashboard/DashboardActivity.kt
- app/src/main/res/layout/app_bar_dashboard.xml
- app/src/main/res/layout/fragment_dashboard_doubts.xml
- app/src/main/res/layout/fragment_dashboard_explore.xml
- app/src/main/res/layout/fragment_dashboard_home.xml
- app/src/main/res/layout/fragment_dashboard_library.xml
- app/src/main/res/layout/fragment_dashboard_my_courses.xml
- app/src/main/res/values/dimens.xml
Signed-off-by: Arnav Gupta <arnav@codingblocks.com>
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
> make dashboard toolbar overlapping

- app/src/main/java/com/codingblocks/cbonlineapp/course/CourseActivity.kt
- app/src/main/java/com/codingblocks/cbonlineapp/course/CourseSectionAllFragment.kt
- app/src/main/res/layout/activity_course.xml
- app/src/main/res/layout/fragment_all_section_course.xml
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
> bottom sheet view all
